Repository hsabouri/42_doom_nukem, pull requests merged in 2019-06, with the labels that each got.

#15 Resolution des petites issues
  srcs/checker_niveau/check_entities.c
  srcs/components/editor_comp/map/draw/entity.c
  srcs/components/hud/help.c
  srcs/components/hud/hud.c
  srcs/components/hud/hud.h
  srcs/editor/in_game/in_game.c
  srcs/event.c
  srcs/game/game.c
  srcs/graphic/teleport.c
  srcs/physic/physic.c
Labels: bug, enhancement

#19 You should not pass
  includes/physic.h
  srcs/physic/collision_gestion.c
  srcs/physic/entities_physic.c
  srcs/physic/teleportation.c
  srcs/physic/tracking_entities.c
  srcs/physic/z_inter.c
Labels: enhancement

#18 Norme of components
  srcs/components/editor_comp/map/assign_entity.c
  srcs/components/editor_comp/map/assign_portal.c
  srcs/components/editor_comp/map/assign_wall.c
  srcs/components/editor_comp/map/class_list.c
  srcs/components/editor_comp/map/draw/draw_map.c
  srcs/components/editor_comp/map/draw/entity.c
  srcs/components/editor_comp/map/draw/pointer_pos.c
  srcs/components/editor_comp/map/draw/portal.c
  srcs/components/editor_comp/map/draw/wall.c
  srcs/components/editor_comp/map/entity_tool.c
  srcs/components/editor_comp/map/index.c
  srcs/components/editor_comp/map/index_childs.c
  srcs/components/editor_comp/map/index_utils.c
  srcs/components/editor_comp/map/map.h
  srcs/components/editor_comp/map/point_tool.c
  srcs/components/editor_comp/map/sector_color_tool.c
  srcs/components/editor_comp/map/selectors/entity.c
  srcs/components/editor_comp/map/selectors/selectors.c
  srcs/components/editor_comp/map/utils.c
  srcs/components/editor_comp/map/wall_tool.c
Labels: clean

#22 fucked up optimisation for the norme of graphics argh
  includes/graphic.h
  srcs/graphic/bresenham.h
  srcs/graphic/bunch.c
  srcs/graphic/bunch/bunch.c
  srcs/graphic/bunch/entity_bunch.c
  srcs/graphic/bunch/singletons.h
Labels: clean

#25 Frozen materials
  Makefile
  endline_op.sh
  includes/structure.h
  includes/structure_clone.h
  lib/libft/Makefile
  lib/libtga/Makefile
  lib/libvec/Makefile
  srcs/components/editor_comp/materials/mat_list.c
  srcs/editor/create/create_material.c
  srcs/game/default.c
  srcs/game/init_mat_1.c
  srcs/save_load/parse_map.c
  srcs/save_load/write_map.c
Labels: enhancement

#26 segfault/20
  srcs/components/hud/in_game_editor/index.c
Labels: bug

#27 version on menu
  textures/convert_png_tga.sh
  textures/menu/.DS_Store
  textures/menu/menu_background.tga
Labels: clean

#29 Norme again
  srcs/event.c
  srcs/game/game.c
  srcs/init.c
  srcs/main.c
  srcs/physic/collision_gestion.c
  srcs/physic/entities_physic.c
  srcs/physic/physic.c
  srcs/physic/teleportation.c
  srcs/physic/z_inter.c
  srcs/save_load/parse_map.c
  textures/hud/in_game_editor.tga
Labels: clean

#31 Replace printf
  srcs/checker_niveau/check_entities.c
  srcs/checker_niveau/check_mats.c
  srcs/checker_niveau/check_portal.c
  srcs/checker_niveau/check_sector.c
  srcs/checker_niveau/check_wall.c
  srcs/checker_niveau/launch_check.c
Labels: clean

#33 Distance fog
  includes/graphic.h
  srcs/graphic/material.c
  srcs/graphic/proj_bis.c
  srcs/graphic/projection.c
  srcs/graphic/render.c
Labels: enhancement

#34 Norme on graphics
  includes/doom.h
  includes/graphic.h
  srcs/components/editor_comp/materials/preview.c
  srcs/graphic/display/display.c
  srcs/graphic/display/display_portal.c
  srcs/graphic/material/get_pixel.c
  srcs/graphic/material/material.c
  srcs/graphic/multi_sprite.c
  srcs/graphic/multi_thread.c
  srcs/graphic/projection.c
  srcs/graphic/render/render.c
  srcs/graphic/render/render_objects.c
Labels: clean

#35 Loose events
  includes/doom.h
  includes/load_save.h
  includes/structure.h
  includes/structure_clone.h
  srcs/components/editor_comp/event_action/entity_list.c
  srcs/components/editor_comp/event_action/ev_ac.h
  srcs/components/editor_comp/event_action/event_list.c
  srcs/components/editor_comp/event_action/index.c
  srcs/components/editor_comp/event_action/second_entity_list.c
  srcs/components/editor_comp/event_action/trigger_list.c
  srcs/components/editor_comp/index.c
  srcs/components/hud/full_empty_life.c
  srcs/components/hud/hud.h
  srcs/components/hud/life.c
  srcs/condition/condition.c
  srcs/condition/condition_tools.c
  srcs/condition/triggers.c
  srcs/condition/triggers.h
  srcs/editor/create/create_sector.c
  srcs/game/default.c
  srcs/game/event_action/animate.c
  srcs/game/event_action/event_action.c
  srcs/game/game.c
  srcs/game/init_map.c
  srcs/game/init_weapons_1.c
  srcs/main.c
  srcs/physic/collision_detec.c
  srcs/physic/entities_physic.c
  srcs/physic/physic.c
  srcs/physic/teleportation.c
  srcs/save_load/default_entity.c
  srcs/save_load/parse.c
  srcs/save_load/parse_entities.c
  srcs/save_load/parse_events_actions.c
  srcs/save_load/write.c
  srcs/save_load/write_events_actions_entities.c
  srcs/save_load/write_player_entities.c
Labels: clean, enhancement

#36 Button entity
  includes/doom.h
  includes/structure.h
  srcs/common/entity_type_to_text.c
  srcs/game/default.c
  srcs/game/event_action/event_action.c
  srcs/game/init_classe.c
  srcs/game/init_mat_1.c
  srcs/game/init_multi_sprite.c
  srcs/load_all_textures.c
  srcs/physic/physic.c
  textures/items/close_door_blue.tga
  textures/items/close_door_green.tga
  textures/items/close_door_purple.tga
  textures/items/close_door_red.tga
  textures/items/open_door_blue.tga
  textures/items/open_door_green.tga
  textures/items/open_door_purple.tga
  textures/items/open_door_red.tga
Labels: clean, enhancement

#38 norme .h + delete lib/test
  includes/doom.h
  includes/editor.h
  includes/graphic.h
  includes/load_save.h
  includes/physic.h
  includes/structure.h
  lib/libft/tests/Makefile
  lib/libft/tests/ft_apush.c
  lib/libft/tests/ft_array_new.c
  lib/libft/tests/ft_array_pop.c
  lib/libft/tests/ft_ashift.c
  lib/libft/tests/ft_listinsert_tests.c
  lib/libft/tests/ft_listjoin_tests.c
  lib/libft/tests/ft_listnew_tests.c
  lib/libft/tests/ft_listnext_tests.c
  lib/libft/tests/ft_listpush_tests.c
  lib/libft/tests/ft_listshift_tests.c
  lib/libft/tests/main.c
  lib/libft/tests/tests.h
  lib/libtga/includes/tga.h
  lib/libvec/tests/Makefile
  lib/libvec/tests/fixed.c
  lib/libvec/tests/float.c
  lib/libvec/tests/main.c
  lib/libvec/tests/tests.h
  lib/libvec/tests/vec.c
  srcs/game/default.c
Labels: clean

#39 Loose events
  includes/doom.h
  includes/graphic.h
  includes/structure.h
  includes/structure_clone.h
  srcs/components/editor_comp/map/draw/entity.c
  srcs/components/editor_comp/map/draw/pointer_pos.c
  srcs/components/editor_comp/map/draw/wall.c
  srcs/components/editor_comp/map/entity_data.c
  srcs/components/editor_comp/map/index.c
  srcs/components/editor_comp/map/index_childs.c
  srcs/components/editor_comp/map/map.h
  srcs/editor/in_game/in_game.c
  srcs/game/event_action/animate.c
  srcs/game/event_action/event_action.c
  srcs/game/game.c
  srcs/game/init_classe.c
  srcs/physic/collision_detec.c
  srcs/physic/physic.c
  srcs/save_load/parse_entities.c
  srcs/save_load/parse_map.c
  srcs/save_load/write_map.c
  srcs/save_load/write_player_entities.c
  textures/ui/entity_data.tga
Labels: enhancement

#41 change entity height via editor
  srcs/editor/in_game/in_game.c
  srcs/editor/in_game/sectors.c
Labels: enhancement

#42 Loose events
  includes/doom.h
  includes/editor.h
  includes/structure.h
  srcs/components/editor_comp/materials/index_2.c
  srcs/components/hud/hud.h
  srcs/components/hud/inventory.c
  srcs/editor/create/create_entity.c
  srcs/editor/create/new_update.c
  srcs/editor/delete/delete.c
  srcs/editor/delete/delete_update.c
  srcs/editor/in_game/sectors.c
  srcs/game/event_action/actions.c
  srcs/game/event_action/event_action.c
  srcs/save_load/default_entity.c
  textures/items/key_card_green.tga
Labels: clean, enhancement

#43 faster texture moving
  srcs/editor/in_game/texture.c
Labels: bug, clean

#44 Sol tex pos
  includes/doom.h
  includes/graphic.h
  includes/structure.h
  includes/structure_clone.h
  srcs/event.c
  srcs/event2.c
  srcs/graphic/material/get_pixel.c
  srcs/graphic/proj_bis.c
  srcs/main.c
  srcs/save_load/parse_textures_sounds.c
Labels: bug

#45 sound + keycard verification + ammo management
  audio/sound/0.ogg
  audio/sound/0_dog.ogg
  audio/sound/1.ogg
  audio/sound/1_open_door.ogg
  audio/sound/2_oof.ogg
  audio/sound/3_salut.ogg
  audio_tmp/sound_tmp/sound_0.ogg
  audio_tmp/sound_tmp/sound_1.ogg
  audio_tmp/sound_tmp/sound_3.ogg
  includes/doom.h
  includes/structure.h
  srcs/components/hud/weapons.c
  srcs/game/event_action/actions.c
  srcs/game/event_action/event_action.c
  srcs/game/init_classe.c
  srcs/game/init_weapons_1.c
  srcs/game/init_weapons_2.c
Labels: clean, enhancement

#48 bug + tool
  includes/doom.h
  includes/editor.h
  includes/weapons.h
  srcs/components/editor_comp/map/assign_portal.c
  srcs/editor/create/create_portal.c
  srcs/game/init_weapons_1.c
  srcs/game/init_weapons_2.c
  srcs/save_load/default_entity.c
Labels: clean, enhancement

#50 grab weapon
  includes/structure.h
  includes/weapons.h
  srcs/common/entity_type_to_text.c
  srcs/game/default.c
  srcs/game/event_action/actions.c
  srcs/game/event_action/event_action.c
  srcs/game/game.c
  srcs/game/init_classe.c
  srcs/game/init_mat_1.c
  srcs/game/init_multi_sprite.c
  srcs/game/init_weapons_1.c
  srcs/load_all_textures.c
  textures/not_in_use.tga
  textures/weapons/claymore/claymore1.tga
  textures/weapons/claymore/claymore2.tga
  textures/weapons/claymore/place_claymore.ogg
  textures/weapons/drop.ogg
  textures/weapons/empty.ogg
  textures/weapons/explosion.ogg
  textures/weapons/grenade/drop_grenade.ogg
  textures/weapons/grenade/goupille_grenade.ogg
  textures/weapons/grenade/grenade0.tga
  textures/weapons/grenade/grenade1.tga
  textures/weapons/grenade/throw_grenade.ogg
  textures/weapons/gun/pistol.ogg
  textures/weapons/gun/reload_pistol_revolver.ogg
  textures/weapons/nyan_gun/nyan_gun.ogg
  textures/weapons/revolver/revolver.ogg
  textures/weapons/switch_weapon.ogg
Labels: enhancement

#53 fix collision entities
  srcs/physic/collision_detec.c
  srcs/physic/physic.c
Labels: bug

#52 segfaut audio linux
  includes/doom.h
  srcs/clean.c
  srcs/components/editor_comp/materials/index_2.c
  srcs/components/hud/inventory.c
  srcs/event.c
  srcs/game/audio.c
  srcs/game/audio_linux.c
  srcs/game/event_action/actions.c
  srcs/game/event_action/event_action.c
  srcs/game/event_action/shooting.c
  srcs/game/game.c
  srcs/game/init_weapons_1.c
  srcs/game/init_weapons_2.c
  srcs/load_all_textures.c
  srcs/main.c
  srcs/save_load/default_entity.c
  textures/items/ammo_secondary.tga
Labels: clean, enhancement

#57 Degats des ennemis
  includes/doom.h
  srcs/game/event_action/actions2.c
  srcs/game/event_action/event_action.c
  srcs/game/game.c
  srcs/physic/collision_detec.c
  srcs/physic/collision_entities.c
  srcs/physic/physic.c
Labels: enhancement
